/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLanguage: typeof import('./../src/components/Icons/carbon-language.vue')['default']
    DarkIcon: typeof import('./../src/components/Icons/dark-icon.vue')['default']
    FormItems: typeof import('./../src/components/FormItems/index.vue')['default']
    LightIcon: typeof import('./../src/components/Icons/light-icon.vue')['default']
    RestoreDown: typeof import('./../src/components/Icons/restore-down.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeType: typeof import('./../src/components/ThemeType/index.vue')['default']
  }
}
