/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/Breadcrumb/index.vue')['default']
    FormItems: typeof import('./../src/components/FormItems/index.vue')['default']
    ProjectConfiguration: typeof import('./../src/components/projectConfiguration/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeColor: typeof import('./../src/components/themeColor/index.vue')['default']
  }
}
