/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/Breadcrumb/index.vue')['default']
    CarbonLanguage: typeof import('./../src/components/Icons/carbon-language.vue')['default']
    CarbonMoon: (typeof import('./../src/components/icons/carbon-moon.vue'))['default']
    CarbonSun: (typeof import('./../src/components/icons/carbon-sun.vue'))['default']
    DarkIcon: typeof import('./../src/components/Icons/dark-icon.vue')['default']
    FormItems: typeof import('./../src/components/FormItems/index.vue')['default']
    LightIcon: typeof import('./../src/components/Icons/light-icon.vue')['default']
    ProjectConfiguration: typeof import('./../src/components/ProjectConfiguration/index.vue')['default']
    RestoreDown: typeof import('./../src/components/Icons/restore-down.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeColor: typeof import('./../src/components/ThemeColor/index.vue')['default']
  }
}
